### ISSUE TITLE
ERROR: An unhandled exception occurred

### ISSUE THREAD

**Issue by greencopper** [tenplus1/ethereal#1]
[MOD] Ethereal - Detected and using Farming Redo mod
22:37:44: ERROR[main]: ========== ERROR FROM LUA ===========
22:37:44: ERROR[main]: Failed to load and run script from 
22:37:44: ERROR[main]: /home/martin/building/minetest/bin/../games/minetest_game/mods/ethereal/init.lua:
22:37:44: ERROR[main]: ...st/bin/../games/minetest_game/mods/ethereal/dirt.lua:117: attempt to call field 'register_stair_and_slab' (a nil value)
22:37:44: ERROR[main]: stack traceback:
22:37:44: ERROR[main]:  ...st/bin/../games/minetest_game/mods/ethereal/dirt.lua:117: in main chunk
22:37:44: ERROR[main]:  [C]: in function 'dofile'
22:37:44: ERROR[main]:  ...st/bin/../games/minetest_game/mods/ethereal/init.lua:46: in main chunk
22:37:44: ERROR[main]: ======= END OF ERROR FROM LUA ========
22:37:44: ERROR[main]: Server: Failed to load and run /home/martin/building/minetest/bin/../games/minetest_game/mods/ethereal/init.lua
22:37:44: ERROR[main]: ERROR: An unhandled exception occurred: ModError: Failed to load and run /home/martin/building/minetest/bin/../games/minetest_game/mods/ethereal/init.lua

In thread 4f2fca00:
/home/martin/building/minetest/src/main.cpp:880: int main(int, char**): Assertion '0' failed.
Debug stacks:
DEBUG STACK FOR THREAD 4f2fca00:
#0  int main(int, char**)
(Leftover data: #1  Dedicated server branch)
Aborted

**Comment by greencopper** [comment]
Running 0.4.11 stable release on Alpine Linux.

**Comment by greencopper** [comment]
I have tried running with --verbose output, but it doesn't provide any helpful information.

Just prior to the error the following is loaded:

04:15:29: VERBOSE[main]: register_item_raw: ethereal:gray_dirt
04:15:29: VERBOSE[main]: ItemDefManager: registering "ethereal:gray_dirt"
04:15:29: VERBOSE[main]: NodeDefManager: registering content id "562": name="ethereal:gray_dirt"
04:15:29: VERBOSE[main]: ItemDefManager: setting alias ethereal:crystal_topped_dirt -> ethereal:crystal_dirt
04:15:29: VERBOSE[main]: ItemDefManager: setting alias ethereal:fiery_dirt_top -> ethereal:fiery_dirt
04:15:29: VERBOSE[main]: ItemDefManager: setting alias ethereal:gray_dirt_top -> ethereal:gray_dirt
04:15:29: VERBOSE[main]: ItemDefManager: setting alias ethereal:green_dirt_top -> ethereal:green_dirt
04:15:29: VERBOSE[main]: register_item_raw: bakedclay:red
04:15:29: VERBOSE[main]: ItemDefManager: registering "bakedclay:red"
04:15:29: VERBOSE[main]: NodeDefManager: registering content id "563": name="bakedclay:red"

**Comment by tenplus1** [comment]
greencopper: I've tried to reproduce the error you see but cannot, everything works fine on my side using the latest version of ethereal and minetest 0.4.10 and 0.4.11...  Please check you are up to date, if so tell me what mods you have running also...
