### ISSUE TITLE
dense (SOLID) jungles

### ISSUE THREAD

**Issue by cyisfor** [tenplus1/ethereal#10]
I think it would be better if the jungle areas had parts that were not filled with tree. More space for vines and jungle grass and running from things lurking under the canopy. As-is you just take an axe and start excavating a jungle tree mine. While that could be an interesting challenge, I suppose, I would really like it if there was a jungle biome that didn't fill almost every scrap of spare land with jungle tree.

I could just be configuring it wrong? I remember solid walls of jungle tree on Xanadu too though, so I don't think it's just me.

**Comment by tenplus1** [comment]
Jungle tree's and giant mushroom's have been tweaked to suit...

**Comment by cyisfor** [comment]
Hey, thanks! I uh, can't run minetest without a segfault, but I do appreciate it if I ever get it working.
