### ISSUE TITLE
Dirt patches below waterlilies

### ISSUE THREAD

**Issue by Xanthin** [tenplus1/ethereal#12]
Currently waterlilies are generated with a dirt node below them because the schematic from the flowers mod is used. This looks a bit out of place to me:
<img src="http://i68.servimg.com/u/f68/18/88/15/78/waterl10.png" title="source: i68.servimg.com" />

Ethereal oceans only use sand so it's maybe better to use an ethereal own schematic for a suitable look:
<img src="http://i68.servimg.com/u/f68/18/88/15/78/waterl11.png" title="source: i68.servimg.com" />

If you like you can look for my changes at Xanthin/ethereal@5b0c6d307a29277c51add5879999852cdcfba023 and pull the patch (if you think it's okay and proper done, I'm not really familiar with the lua table thing after just some days playing with it) or apply it in your own way . ;)

**Comment by tenplus1** [comment]
Added with some edits :) thanks
