### ISSUE TITLE
Less flooding with river water instead of water?

### ISSUE THREAD

**Issue by Xanthin** [tenplus1/ethereal#13]
Maybe, if sources should be produced when smelting snow and ice, it is better to use the river water. If I'm not wrong it is designed for better controled water flow (not renewable, lower spread). Also its lighter color fits good into snowy regions. 

I tested it with two `default:water_source` placed in X (for renewable effect) and after 2 minutes removed the sources. After most of it flow down I placed two `default:river_water_source` at the same spots and waited again.
The picture shows the river water stream, very slim and not extrem long. You see the dirt/green grass patches left by the previous `default:water_source` flooding (at the left side there is still the normal water flowing down)

<img src="http://i68.servimg.com/u/f68/18/88/15/78/screen10.jpg" title="source: i68.servimg.com" />
Just in case my change: 6ba88a1fdd309357885bf4aa44bccd897f2e2804

**Comment by tenplus1** [comment]
Good idea, any wate above sea level will not melt into river water.

**Comment by HybridDog** [comment]
l think for river water river ice should be added. Frozen water next to a waterfall, which appears in rivers, looks very interesting (structures), whereas the top of a frozen lake is just a flat place.
