### ISSUE TITLE
Use fence registration function

### ISSUE THREAD

**Issue by HybridDog** [tenplus1/ethereal#16]
l made a mod which allows adding fences which have a lot parts of the node they are made of in their node definition.
https://github.com/HybridDog/fence_registration
lt also registers the fence as a node from the mod where its origin belongs to.
If you decide to use it, you 
* make the fences always have the newest properties of the nodes they are made of
* can short code
* can find the fences in the sorted creative inventory next to the other nodes of the mod they belong to

you also
* need to add the mod as (maybe optional) dependency
* need to add aliases for the current ones (fences.lua)

**Comment by tenplus1** [comment]
Ethereal NG will be released shortly which uses 0.4.13 dev's fence and gate registration functions.
