### ISSUE TITLE
Saplings aren't in sapling group

### ISSUE THREAD

**Issue by MT-Modder** [tenplus1/ethereal#26]

**Comment by tenplus1** [comment]
The 'sapling' group is only needed by default abm to grow tree's whereas the 'ethereal_sapling' group handles ethereal tree growth and burning of said saplings as fuel :)

**Comment by MT-Modder** [comment]
Yes but mods use it for craft recipes and default saplings use nodetimers now.

**Comment by tenplus1** [comment]
Will look into it, which mods use sapling group most?

**Comment by MT-Modder** [comment]
Mesecons mostly. Thanks dude. Yeah at first I thought it would mess up ethereal's grow routine but noticed minetest_game had been completely redone it.
