### ISSUE TITLE
Vine decay and more moretrees, plantlife and technic compatibility

### ISSUE THREAD

**Issue by ClockGen** [tenplus1/ethereal#31]
Vines remain floating after their parent block is destroyed.

Also, moretrees and ethereal have many duplicate items, since ethereal already implements some compatibility for moretrees and plantlife, could more compatibility be added to allow moretrees craft schematics and vise versa? Currently, there are duplicate palm trees, duplicate trunk, leaves and planks nodes, duplicate coconuts and palm saplings, though they all share same textures.

Plantlife modpack also features vines mod that add growing vines and craft schematics for them which uses vines group.

Technic mod have same crafting schematic for oil extract as ethereal have for vine node (6 nodes of leaves group) and overrides it.

**Comment by tenplus1** [comment]
Vines are simple, they have no abm's associated for growth or destruction so simply decoration...  Moretree's will place it's own trees if enabled but genereally ethereal is run without it active so uses it's own nodes more...  Lastly the vine recipe was changed to an X pattern so it wouldnt interfere with homedecor:oil_extract recipe.
