### ISSUE TITLE
Vines are not Flamable

### ISSUE THREAD

**Issue by midnightpizza** [tenplus1/ethereal#32]
Vines should burn like the trees they were spawned with if set on fire. (considering fire mod is enabled)
As of now, when burning down a lot of shrubbery, its just as much grief to use lava than it is what is left, weird scarry looking floaty vines.
![fire](https://user-images.githubusercontent.com/33229270/32416575-b4496cb2-c24b-11e7-90f8-0c9d641493e6.png)

**Comment by orbea** [comment]
I think the vines should drop if the tree they were connected to vanishes.

**Comment by tenplus1** [comment]
changed, thanks :)
