### ISSUE TITLE
Grass side tiles should not be tileable

### ISSUE THREAD

**Issue by HybridDog** [tenplus1/ethereal#35]
When using bumpmapping with parallax occlusion, ethereal grass side tiles look wrong.
It can be fixed like in default: https://github.com/minetest/minetest_game/blob/c2001b3b52fa6971c323cfcf0e35c27d4db5149f/mods/default/nodes.lua#L416

![screenshot_20180303_152813](https://user-images.githubusercontent.com/3192173/36935411-bf9d9896-1ef7-11e8-85bb-55478480505f.png)
For reference: https://github.com/tenplus1/ethereal/blob/0d311c06a207c8ad44ae5090a1a3f01f7959fbc5/dirt.lua#L60

**Comment by tenplus1** [comment]
Changed, thanks :)
