### ISSUE TITLE
Bamboo sapling is not a "proper" sapling → bonemeal problems

### ISSUE THREAD

**Issue by h-v-smacker** [tenplus1/ethereal#36]
With the current definition, the bamboo sapling isn't added to the "sapling" group, only "ethereal_sapling". Meanwhile, the bonemeal mod (the one with mulch) checks for belonging to "sapling" group, and bamboo sprout fails that test, even though it is added to the appropriate mod.lua definition for ethereal plant life.

So the bamboo sapling should also have "sapling = 1" in its group definition (I imagine this is a better option, because who knows which mods might also test for that), or the bonemeal mod should check for "ethereal_sapling" group membership as well.

This really should be fixed, because bamboo is awesome.

**Comment by tenplus1** [comment]
Fixed, thanks for noticing :)
