### ISSUE TITLE
Biomes probably need the new naming scheme

### ISSUE THREAD

**Issue by poet-nohit** [tenplus1/ethereal#4]
I keep running into errors when ethereal tries to register decorations, at least until I fixed up the naming. See https://github.com/poet-nohit/minetest-spiffy/commit/1a77a23014471ddd73ec0468940ea416fd5055ea

**Comment by tenplus1** [comment]
I tried the new naming and it caused all sorts of problems with the latest 0.4.12 dev version so returned to the old naming scheme...  Will look into maybe adding "ethereal_" instead...
