### ISSUE TITLE
Trees have hanging fruit and a lack of variety

### ISSUE THREAD

**Issue by poet-nohit** [tenplus1/ethereal#6]
I noticed that schematics tend to have param2 = 1 in them where you have fruit which causes them to remain in the air after you remove the tree. I have some tree models (for the apple tree, anyway) and a few code changes to rectify that.

https://github.com/poet-nohit/minetest-spiffy/commit/7e6f08335bd83281fbe7169c2b8ace579ca9a9a7

**Comment by tenplus1** [comment]
I will soon be working on schematic updates to allow random generation of all tree's without the need for separate models, the same way Paramat does in his BiomesDev mod: https://github.com/paramat/biomesdev
